Fix import error in scientific tests
The following command was failing:

```
pytest -s -k scientific/test_projections
```

with the error:

```
examples/test_neurodamus.py:8: in <module>
    from neurodamus.utils import setup_logging
E   ImportError: cannot import name 'setup_logging' from 'neurodamus.utils'
```

This seems to be because the `setup_logging` method moved from
`neurodamus.utils` to `neurodamus.utils.logging` at some point.