Fix load balancing of SONATA circuits by avoiding the selection of a virtual population
## Context
Fix load balancing of SONATA circuits by avoiding the selection of a virtual population

## Scope
Before when trying to run the `SSCx_O1` circuit with `main` I got:

```
[STEP] ================ CALCULATING LOAD BALANCE ================
[STEP] Computing Load Balance
[INFO] Activating experimental LB for Sonata circuit 'POm'
[INFO] Load Balancing ENABLED. Mode: WholeCell
[INFO] Creating load balance dir sim_conf/_loadbal_3561a90976
[INFO]  => No complexity files for current circuit yet
[INFO]  => Target Cx reusing is not available.
[INFO] Could not reuse load balance data. Doing a Full Load-Balance
[INFO] Generating mcomplex.dat...
[CRITICAL] (rank 27) Unhandled Exception. Terminating...
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/commands.py", line 75, in neurodamus
    Neurodamus(config_file, True, log_level, **options).run()
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/node.py", line 1665, in __init__
    self._instantiate_simulation()
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/node.py", line 1766, in _instantiate_simulation
    self._build_model()
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/node.py", line 1677, in _build_model
    load_bal = self.compute_load_balance()
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/core/_utils.py", line 35, in mpi_ok_wrapper
    res = f(*args, **kw)
  File "/gpfs/bbp.cscs.ch/ssd/apps/bsd/2023-02-23/stage_externals/install_gcc-12.2.0-skylake/python-3.10.8-rvn6l5/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/gpfs/bbp.cscs.ch/data/scratch/proj16/magkanar/BBPP154-67/neurodamus-py/neurodamus/node.py", line 387, in compute_load_balance
    cell_dist.finalize()
AttributeError: 'VirtualCellPopulation' object has no attribute 'finalize'
```

Because the `POm` population was virtual. From the `circuit_config.json`:

```
"populations": {
                    "POm": {
                        "type": "virtual"
                    }
                }
```

After this change we have:

```
[STEP] ================ CALCULATING LOAD BALANCE ================
[STEP] Computing Load Balance
[INFO] Activating experimental LB for Sonata circuit 'S1nonbarrel_neurons'
[WARNING] Your simulation has a very high count of cells per CPU. Please consider launching it in a larger MPI cluster
[INFO] Load Balancing ENABLED. Mode: WholeCell
[INFO] Creating load balance dir sim_conf/_loadbal_6949fe3fe3
[INFO]  => No complexity files for current circuit yet
[INFO]  => Target Cx reusing is not available.
[INFO] Could not reuse load balance data. Doing a Full Load-Balance
[INFO] Reading Nodes (METype) info from '/gpfs/bbp.cscs.ch/project/proj83/jira-tickets/NSETM-1948-extract-hex-O1/data/O1_data_physiology/S1nonbarrel_neurons/nodes.h5'
[INFO]  -> Distributing 'S1nonbarrel_neurons:hex0' target cells Round-Robin
[INFO]  => Loaded info about 30190 target cells (out of 211712)
[INFO] Generating mcomplex.dat...
[INFO] Finalizing cells... Gid offset: 0
[INFO]  > Instantiating cells... (126 in Rank 0)
```

## Testing
https://bbpgitlab.epfl.ch/hpc/sim/blueconfigs/-/merge_requests/98

## Review
* [x] PR description is complete
* [x] Coding style (imports, function length, New functions, classes or files) are good
* [ ] Unit/Scientific test added 
* [ ] Updated Readme, in-code, developer documentation