[HPCTM-1687]: fix error of checking np.recarray None or empty
## Context
This MR fixed the error seen in HPCTM-1687 while checking a `np.reccarry`with more than element is None or empty. It happens when multiple synapses are added to the same connection. 
```
>>> x = np.recarray(2, dtype=np.dtype({"names": ("x", "y"), "formats": ["f8"]*2}))
>>> not bool(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> x is None or len(x) == 0
False
```

## Scope
In `connection.py: add_synapses()`, use `if self._synapse_params is None or len(self._synapse_params) == 0` to check the recarray is None or empty

## Testing
New unit test `tests/test_connection.py::test_add_synapses`

Create connections with config file `v5_sonata/simulation_config_mini.json` and add a dummy synapse parameter array to one of the connections.

## Review
* [x] PR description is complete
* [x] Coding style (imports, function length, New functions, classes or files) are good
* [x] Unit/Scientific test added 
* [ ] Updated Readme, in-code, developer documentation